services:
  - type: web
    name: proyecto-volare
    env: python
    plan: free
    rootDirectory: E4a/proyectoVolare
    workingDirectory: E4a/proyectoVolare
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: gunicorn proyectoVolare.wsgi