services:
  - type: web
    name: proyecto-volare
    env: python
    plan: free
    rootDirectory: E4a/proyectoVolare
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn proyectoVolare.wsgi
