services:
  - type: web
    name: proyecto-volare
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn proyectoVolare.wsgi:application"
    rootDirectory: E4a/proyectoVolare
    envVars:
      - key: DEBUG
        value: False
